export const data = [
    {
      name: "Ace Dune",
      author: "Frank Herbert",
      description: "Dune is set far into the future, in an intergalactic feudal society where powerful noble houses fight for control over resources, armies, and planetary power. House Atreides is ordered to take control of Arrakis, a barren desert planet with a brutal climate. Arrakis is the only place to mine melange, a natural resource that produces a psychoactive drug called spice, which allows humanity to unlock their minds. On Arrakis, House Atreides is betrayed by rival House Harkonnen, which sets off a battle over the valuable planet. The planet itself is inhabited by giant sandworms and a native population known as Fremen, who, over the generations, have learned to survive with water as their most precious resource and currency. When House Atreides scion Paul is targeted as a potential messiah to lead the planet—and galaxy—toward a new era, an epic story of war, betrayal, and mysticism unfolds.",
      bookPicture: "/src/media/bookPicture1.jpg",
      id: "1",
    },
    {
      name: "Ace Dune Messiah",
      author: "Frank Herbert",
      description: "In Herbert's first sequel, Paul Atreides, now known as Muad'Dib, rules the known universe as the most powerful emperor of all time. Worshipped as a messiah by the people of Arrakis, Paul faces enmity from the warring political houses under his control. Is any one ruler meant to have such absolute power? In Dune: Messiah, Herbert unmakes his previous novel, all while warning, No more terrible disaster could befall your people than for them to fall into the hands of a hero.",
      bookPicture: "/src/media/bookPicture2.jpg", 
      id: "2",
    },
    {
      name: "Ace Children of Dune",
      author: "Frank Herbert",
      description: "Children of Dune picks up with Leto and Ghanima Atreides, the twin children of Paul Atreides, nine years after their father's mysterious disappearance into the wastelands of Arrakis. The twins' prophetic abilities are coveted by their manipulative aunt Alia, who rules the Empire, but these two young prophets refuse to be anyone's pawns.",
      bookPicture: "/src/media/bookPicture3.jpg", 
      id: "3",
    },
    {
      name: "Ace God Emperor of Dune",
      author: "Frank Herbert",
      description: "3500 years after the events of Children of Dune, the once-desert planet of Arrakis is now a lush paradise, and Leto Atreides sits on the throne. Millennia ago, Leto merged with a sandworm to grant himself immortality, but the cost to his humanity has been enormous. Can a rebellion led by Siona, a rival relative, unseat this fearsome despot?",
      bookPicture: "/src/media/bookPicture4.jpg", 
      id: "4",
    },
    {
      name: "Ace Heretics of Dune",
      author: "Frank Herbert",
      description: "Leto Atreides is dead, Arrakis (now called Rakis) is once again a desert wasteland, and the Empire has fallen into ruin. A young girl named Sheeana seems to fulfill a prophecy foretold by the late God Emperor, sending religious fervor through the galaxy. Is Sheeana destined to return the Empire to its former glory?",
      bookPicture: "/src/media/bookPicture5.jpg", 
      id: "5",
    },
    {
      name: "Ace Chapterhouse: Dune",
      author: "Frank Herbert",
      description: "In Herbert's final Dune novel, Arrakis has been destroyed, and the fate of the Empire rests in the hands of a mysterious matriarchal order known as the Bene Gesserit. On the planet Chapterhouse, the sisters are breeding sandworms and seeking to control spice production, with the goal of remaking the galaxy for a brighter future.",
      bookPicture: "/src/media/bookPicture6.jpg",
      id: "6",
    },
    {
      name: "Del Rey House Atreides",
      author: "Brian Herbert and Kevin J. Anderson",
      description: "Brian Herbert and Kevin J. Anderson's Prelude to Dune trilogy begins with this story of the generation before Dune; namely, Leto Atreides, father of Paul. In House Atreides, we see how Leto's rivalries and relationships sowed the catalyzing events of Dune.",
      bookPicture: "/src/media/bookPicture7.jpg",
      description: "",
      id: "7",
    },
    {
      name: "Del Rey House Harkonnen",
      author: "Brian Herbert and Kevin J. Anderson",
      description: "In House Harkonnen, Leto Atreides' longtime rival, the Baron Vladimir Harkonnen, comes into view. We also meet Abulurd Rabban, brother and foil to the Baron. Turns out, there are good people in House Harkonnen—who knew?",
      bookPicture: "/src/media/bookPicture8.jpg",
      id: "8",
    },
    {
      name: "Del Rey House Corrino",
      author: "Brian Herbert and Kevin J. Anderson",
      description: "In House Corrino, Brian and Anderson conclude their prequel series, bringing the story up to the climactic events set to unfold in Dune. This tapestry of politics, warmongering, and spice battles ends with the birth of Paul Atreides, teeing us up to the saga we know and love (and now, have already read).",
      bookPicture: "/src/media/bookPicture9.jpg",
      id: "9",
    },
    {
      name: "The Butlerian Jihad",
      author: "Brian Herbert and Kevin J. Anderson",
      description: "Working from Frank Herbert's notes, titled 'Dune 7,' Brian and Anderson again expanded the series in Legends of Dune, a new trilogy. The first installment, The Butlerian Jihad, digs into an event Herbert often referred to, but never captured at scale: the long-ago war where humans fought for their freedom from 'the thinking machines.' Set 10,000 years before Dune, the familiar chess pieces come into view in this volume.",
      bookPicture: "/src/media/bookPicture10.jpg",
      id: "10",
    },
    {
      name: "The Machine Crusade",
      author: "Brian Herbert and Kevin J. Anderson",
      description: "Legends of Dune continues with The Machine Crusade, set two decades after The Butlerian Jihad. The thinking machines fight back, refusing to go quietly into that good night; meanwhile, on Arrakis, a band of outlaws take their first steps to becoming the Fremen, a race of people that OG Dune fans know and love.",
      bookPicture: "/src/media/bookPicture11.jpg",
      id: "11",
    },
    {
      name: "The Battle of Corrin",
      author: "Brian Herbert and Kevin J. Anderson",
      description: "Check out that sandworm on the cover! The Legends of Dune trilogy concludes with The Battle of Corrin, which tees up a final apocalyptic showdown between humans and robots. Fans of Dune know how this one ends, but it sure is fun to see how Herbert and Anderson get there.",
      bookPicture: "/src/media/bookPicture12.jpg",
      id: "12",
    },
    {
      name: "Hunters of Dune",
      author: "Brian Herbert and Kevin J.Anderson",
      description: "Dune Sequels, a two-volume spin-off series, concludes the storyline from Herbert's six original novels, with insight from a long-lost outline that was found hidden in one of the author's safety deposit boxes. In Hunters of Dune, we pick up with the escaping fugitives last seen at the end of Chapterhouse Dune as they strengthen their powers and fight for the future of the human race.",
      bookPicture: "/src/media/bookPicture13.jpg", 
      id: "13",
    },
    {
      name: "Sandworms of Dune",
      author: "Brian Herbert and Kevin J. Anderson",
      description: "Herbert and Anderson tie up more burning questions in this second volume of the Dune Sequels series: namely, the future of Arrakis and the outcome of the war between Man and Machine.",
      bookPicture: "/src/media/bookPicture14.jpg", 
      id: "14",
    },
    {
      name: " Paul of Dune",
      author: "Brian Herbert and Kevin J. Anderson",
      description: "The Heroes of Dune spin-off series opens with this tale of Paul Atreides, set between Dune and Dune Messiah. Dune ends with Paul ruling Arrakis, while Dune Messiah opens with Paul ruling the galaxy. Just how did Paul gain control of the Empire? Read Paul of Dune to find out.",
      bookPicture: "/src/media/bookPicture15.jpg",
      id: "15",
    },
    {
      name: "The Winds of Dune",
      author: "Brian Herbert and Kevin J. Anderson",
      description: "Heroes of Dune continues with this second and final installment, set after the events of Dune Messiah. The Winds of Dune picks up after Paul Atreides' disappearance into the Arrakis desert, leaving the Empire in crisis and the line of succession in question. Who will hold everything together?",
      bookPicture: "/src/media/bookPicture16.jpg",
      id: "16",
    },
    {
      name: "Sisterhood of Dune",
      author: "Brian Herbert and Kevin J. Anderson",
      description: "The Great Schools of Dune trilogy opens with Sisterhood of Dune, set almost a century after the game-changing Battle of Corrin. With the thinking machines destroyed, political and religious movements rise, teeing up an epic conflict between reason and faith. You'll want to read this one to prepare for HBO's upcoming Dune: The Sisterhood.",
      bookPicture: "/src/media/bookPicture17.jpg", 
      id: "17",
    },
    {
      name: "Mentats of Dune",
      author: "Brian Herbert and Kevin J. Anderson",
      description: "With the thinking machines destroyed, a new school opens to teach humans the efficient techniques of thinking machines. But the Butlerian jihadists staunchly oppose any machinist way of life, and pick a dangerous fight with the Mentat School. What ensues is an epic showdown for humanity's future, with a potential dark age at stake.",
      bookPicture: "/src/media/bookPicture18.jpg",
      id: "18",
    },
      {
      name: "Navigators of Dune",
      author: "Brian Herbert and Kevin J. Anderson",
      description: "Want to learn more about the Bene Gesserit sisterhood from Herbert's original novels? Then Navigators of Dune is the book for you. In this third and final volume of the Great Schools of Dune trilogy, we learn about the origins of the Bene Gesserit sisterhood, and see their secretive way of life develop. This one will be important when Sisterhood of Dune hits HBO Max.",
      bookPicture: "/src/media/bookPicture19.jpg",
      id: "19",
    },
    {
      name: "The Duke of Caladan",
      author: "Brian Herbert and Kevin J. Anderson",
      description: "The latest trilogy from Herbert and Anderson, The Caladan Trilogy, begins with The Duke of Caladan, a prequel about the life of Leto Atreides. Just how did the ruler of a quiet planet become such a power player in a galactically fateful story? If that's the question on your mind, this is the book you ought to hit next.",
      bookPicture: "/src/media/bookPicture20.jpg",
      id: "20",
    },
    
  ];
  